version: '3.0'

services:

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/other.conf:/etc/nginx/other.conf
      - ./nginx/html:/stuff/html
      - ./nginx/css:/stuff/css
      - ./nginx/hosts:/etc/hosts
    ports:
      - "80:80"

    environment:
      - NGINX_PORT=80
    extra_hosts:
      - "some:192.168.1.4"
      - "google:64.233.165.100"

volumes:
  nginx: